### ISSUE TITLE
broken github link

### ISSUE THREAD

**Issue by rzr** [iotivity/iotivity#1]
On:
https://github.com/iotivity/iotivity

I see:
{
To contribute code to the project, please visit https://www.iotivity.org/get-involved. https://www.iotivity.org
}

I should be:

https://iotivity.org/get-involved

cc: @mwichmann

**Comment by mwichmann** [comment]
Well, I can't fix that... don't know if there is anyone who can.  Will this location continue to be a mirror, now of the gitlab instance?  part of the change needs to be made there (the bit in `README.md`), the other bit needs to be made by whoever has rights to the github "project".

**Comment by OICAdmin** [comment]
It should be fixed now.
Thanks,
-Rami

**Comment by rzr** [comment]
Thanks
